# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-09-18 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20210918_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='picture',
            field=models.ImageField(null=True, upload_to='album'),
        ),
    ]
